[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[env]
TERM ="xterm-256color"

[shell]
args = ["-l", "-c", "tmux attach || tmux new -A -s home"]
program = "/bin/zsh"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
opacity = 0.9999

[window.padding]
x = 4
y = 4
